site_name: My MSc
site_author: Eduardo Furlan
copyright: CC BY-NC 4.0 License
repo_name: efurlanm/msc22
repo_url: http://github.com/efurlanm/msc22
docs_dir: docs-src
site_dir: docs
use_directory_urls: false  # need for inline html and dir navigation
theme:
    name: material
    palette:
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
        primary: teal
        accent: teal
    features:
        - header.autohide
plugins:
    - mkdocs-jupyter
markdown_extensions:
    - def_list
    - md_in_html
    - tables
extra_css:
    - css/extra.css
exclude_docs: |
    .ipynb_checkpoints
    .git
