site_name: MSc
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/msc22/
copyright: CC BY-NC 4.0 License
repo_name: msc22
repo_url: http://github.com/efurlanm/msc22/
docs_dir: docs-src
site_dir: docs
theme:
    name: material
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: teal
        accent: teal
    font: false
    features:
        - header.autohide
plugins:
    - search
markdown_extensions:
    - def_list
    - md_in_html
    - tables
extra_css:
    - css/extra.css
exclude_docs: |
    .*
